In [17]:
import numpy as np

print("shape:",a.shape)
print("\ndimension:",a.ndim)
print("\ndata type:",a.dtype.name)
print("\nsize:",a.size)
print("\ntype:",type{a})

In [29]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [30]:
a=np.array([1,2,3])
d=a.copy()
print(d)
b=a
c=a
b[0]=5
print(a,b,c)

[1 2 3]
[5 2 3] [5 2 3] [5 2 3]


In [32]:
a=np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:4])


1
[1 2 3 4]


In [35]:
reverse_array=a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


In [40]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[1,1])
print(b[:,1])
print(b[1,:])
print(b[1,1:4])
print(b[-1,:])
print(b[:,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]
